### ISSUE TITLE
Allow article from file

### ISSUE THREAD

**Issue by dg01d** [cweiske/shpub#12]
As someone who now uses shpub for almost all my posting, I thought it worthwhile to ask:

Could it be enhanced by allowing article posting from a file? In much the same way that photos/images are uploaded by -f, similar could be done with articles and text files. I've noted that the client seems to have a hard limit of file size in normal use, and this could be avoided by calling a file.

**Comment by cweiske** [comment]
This is already possible, see https://github.com/cweiske/shpub#create-a-note
