### ISSUE TITLE
Bad Request received during connect due to missing 'me' query string parameter

### ISSUE THREAD

**Issue by ngm** [cweiske/shpub#14]
shpub: 0.7.0
Wordpress: 4.9.8
indieauth plugin: 3.1.4

When I connected with 

```
shpub connect https://doubleloop.net
```
and allowed the connection, I was redirected to:

> http://127.0.0.1:12345/callback?code=asdfsomecode&state=1234567890

which gave me a Bad Request.

It looks to be because [here](https://github.com/cweiske/shpub/blob/master/src/shpub/Command/Connect.php#L282) we're expecting `me` to be on the query string, but it isn't.  I added `&me=https://doubleloop.net` and it connected successfully.

I'm not really sure how the flow works, but https://indieauth.com/developers seems to suggest you won't get `me` back on the redirect?

**Comment by cweiske** [comment]
This is indeed a bug. The current IndieAuth spec does not require that parameter anymore in the authentication response: https://www.w3.org/TR/indieauth/#authentication-response

**Comment by cweiske** [comment]
This actually was one time in the spec, but removed in 2017-12:
https://indieweb.org/wiki/index.php?title=authorization-endpoint&diff=42612&oldid=42610

Reason for the removal was https://github.com/aaronpk/Quill/issues/79
