### ISSUE TITLE
Can't get access token

### ISSUE THREAD

**Issue by frankmeeuwsen** [cweiske/shpub#15]
I connected to my testserver (WordPress installation with IndieAuth plugin) and I got the message to open a specific URL. After logging in and authorization of the script on the site, I got the message in my shell

"PHP Notice:  Undefined index: me in phar:///usr/local/bin/shpub/src/shpub/Command/Connect.php on line 103

Notice: Undefined index: me in phar:///usr/local/bin/shpub/src/shpub/Command/Connect.php on line 103
Failed to fetch access token
Server responded with HTTP status code 400
{"error":"invalid_request","error_description":"The request is missing one or more required parameters"}"

What to do next?

**Comment by cweiske** [comment]
Closing because it's probably outdated.
