### ISSUE TITLE
add query support

### ISSUE THREAD

**Issue by aaronpk** [cweiske/shpub#2]
It would be great to add [query support](https://www.w3.org/TR/micropub/#source-content) for finding:

* all properties in a post `q=source&url=...`
* specific properties of a post `q=source&properties[]=category&url=...`

**Comment by cweiske** [comment]
syndication endpoint querying would also help for micropub.rocks client test 105.

**Comment by cweiske** [comment]
I don't have an endpoint which supports query, so I won't implement it in shpub. Feel free to re-open with a patch.
