### ISSUE TITLE
problem finding media endpoint

### ISSUE THREAD

**Issue by aaronpk** [cweiske/shpub#3]
I can't seem to get the client to discover the media endpoint. From what I can tell, the [config request](https://github.com/cweiske/shpub/blob/master/src/shpub/Config/Endpoints.php#L89) is never sent.

**Comment by cweiske** [comment]
It does that when it thinks that the endpoint information is incomplete (authorization endpoint OR token endpoint OR micropub endpoint URL is not set) in src/Config/Hosts.php.

So when it did not discover the endpoint at the beginning for whatever reason, then it will not try again.

**Comment by aaronpk** [comment]
By the time it has an access token, then the endpoint information is "complete", since it would have had to find the authorization endpoint, token endpoint, and micropub endpoint already. I think [this condition](https://github.com/cweiske/shpub/blob/master/src/shpub/Config/Host.php#L50) is never false.

**Comment by aaronpk** [comment]
My mistake, I was misreading the code. It seems to find the media endpoint just fine.

**Comment by gerwitz** [comment]
I'm having the same problem, but missing something here. When I use `connect` I end up with an .ini file that contains `server=`, `user=`, and `token=` and non-media request work as expected.

But as with this issue, I cannot seem to get shpub to generate a config request to discover the media endpoint.

**Comment by cweiske** [comment]
The media endpoint is stored in the cache file, which you can find at `~/.cache/shpub/*.ini`.
