### ISSUE TITLE
Support sending likes with syndication target

### ISSUE THREAD

**Issue by miklb** [cweiske/shpub#9]
I tried `like https://github.com/snarfed/wordpress-micropub -x mp-syndicate-to=https://silo.pub/micropub?access_token=accesstoken` and get the error `no matches found: mp-syndicate-to=https://silo.pub/micropub?access_token=accesstoken`

If I send a like without the `-x mp-syndicate-to` it works fine.

I'm attempting to do a like and use silo.pub to star a GitHub repo.

Thanks!

**Comment by cweiske** [comment]
Which endpoint do you use? What do you get when adding the `--debug` parameter as in `shpub --debug like ...`?

I see here that the `mp-syndicate-to` property is added to the request, which is as it should be. I'd think it's a problem with the endpoint, but I don't have enough info for that.

**Comment by miklb** [comment]
Thanks, I'll test with debug, I haven't looked at this in a couple of months. I'm sending to my WordPress micropub endpoint which like I said, accepts the like without the syndication in shpub. I can do syndication targets just fine with Quill, it just doesn't support syndication targets for likes.

**Comment by miklb** [comment]
with `--debug` I get the same error `no matches found`

**Comment by cweiske** [comment]
Is that syndicate-to URL listed when you execute `$ shpub targets`?

**Comment by miklb** [comment]
holy crap, it worked this time. I had the wrong token in my last test, so after checking `targets` and using that the like posted. 

Thank you so much!

this was with 0.5.2

**Comment by miklb** [comment]
Let me clarify, it created the like but I'm not sure on the WordPress end I'm getting the syndication target set, but that might be on my side of things.
